var projects = {
    "bookmyshow": {
        access: 'bookmyshow',
        layout: 'project1',
        title: 'Case Study : BookMyShow Mobile Apps | LeftShift | we create loveable apps for ios, android and the web',
        description: 'Leftshift was involved with the usability, design, and development of the BookMyShow mobile applications',
        name: 'BookMyShow',
        tagline: 'Ticketing for mobile devices',
        para1: 'BookMyShow.com is the biggest ticketing web site in India, with over a 90% market share. We advised and worked with them for over a year, to rebuild their mobile experience from scratch.',
        para2: 'We were involved with the usability, design, and development of the project.',
        mainurl: 'https://itunes.apple.com/in/app/bookmyshow-movie-event-play/id405894842?mt=8',
        appstoreurl: 'https://itunes.apple.com/in/app/bookmyshow-movie-event-play/id405894842?mt=8',
        googleplayurl: 'https://play.google.com/store/apps/details?id=com.bt.bms&hl=en',
        screenshot: 'https://leftshift.io/images/bms/bookmyshow-main.png',
        alttext: 'Here are screenshots of the BookMyShow mobile applications. BookMyShow is now one of the most popular apps in the AppStore',
        url: '/bookmyshow-mobile-apps',
    },
    "peppertap": {
        access: 'peppertap',
        layout: 'project2',
        title: 'Case Study : Peppertap Mobile Apps | LeftShift | we create loveable apps for ios, android and the web',
        description: 'Leftshift was involved with the development of iOS app for Peppertap',
        name: 'Peppertap',
        tagline: 'Order Groceries Online',
        para1: 'PepperTap brings you the power and convenience of ordering grocery and fruits & vegetables in your hands. A few taps on the phone and within 2 hours, or at your chosen time slot, you will see the products knocking at your door!',
        para2: 'We were involved with the development of the iOS app for PepperTap.',
        mainurl: 'https://itunes.apple.com/in/app/peppertap-online-grocery/id963634124?mt=8',
        appstoreurl: 'https://itunes.apple.com/in/app/peppertap-online-grocery/id963634124?mt=8',
        screenshot: 'https://leftshift.io/images/peppertap/peppertap-main.png',
        alttext: 'Here are screenshots of the Peppertap mobile applications. This app helps you order groceries from anywhere.',
        url: '/peppertap-mobile-apps',
    },
    "faasos": {
        access: 'faasos',
        layout: 'project1',
        title: 'Case Study : Faasos Mobile Apps | LeftShift | we create loveable apps for ios, android and the web',
        description: 'Leftshift was involved with the usability, design, and development of the Faasos mobile applications',
        name: 'Faasos',
        tagline: 'Fastest Food Delivery',
        para1: 'Faasos is your personal kitchen. It serves all meals, 365 days a year and delivers across 10 cities across India already.',
        para2: 'We were involved with the usability, design, and development of the project.',
        mainurl: 'https://play.google.com/store/apps/details?id=com.done.faasos&hl=en',
        appstoreurl: 'https://itunes.apple.com/in/app/faasos-food-order-delivery/id808796222?mt=8',
        googleplayurl: 'https://play.google.com/store/apps/details?id=com.done.faasos&hl=en',
        screenshot: 'https://leftshift.io/images/faasos/faasos-main.png',
        alttext: 'Here are screenshots of the Faasos mobile applications. It helps you order food anywhere in India.',
        url: '/faasos-mobile-apps',
    },
    "citrus": {
        access: 'citrus',
        layout: 'project2',
        title: 'Case Study : Citrus Mobile Apps | LeftShift | we create loveable apps for ios, android and the web',
        description: 'Leftshift was involved with the development of iOS and Android apps for Citrus',
        name: 'Citrus Cube',
        tagline: 'Pay people, Pay Bills, Do Good',
        para1: 'Citrus Cube is a Personal Payments Manager that helps you with your bill payments, recharges, bill tracking and even lets you set reminders for your DTH, gas, electricity, postpaid, pre-paid, landline bills etc.',
        para2: 'We were involved with the development of the iOS and Android apps for Citrus.',
        mainurl: 'https://play.google.com/store/apps/details?id=com.citruspay.cube&hl=en',
        appstoreurl: 'https://itunes.apple.com/in/app/cube-bill-payment-recharge/id961089570?mt=8',
        googleplayurl: 'https://play.google.com/store/apps/details?id=com.citruspay.cube&hl=en',
        screenshot: 'https://leftshift.io/images/citrus/citrus-main.png',
        alttext: 'Here are screenshots of the Citrus Cube mobile applications. It helps you pay people, bills and do good.',
        url: '/citrus-mobile-apps',
    },
    "iifl": {
        access: 'iifl',
        layout: 'project1',
        title: 'Case Study : IIFL Mobile Apps | LeftShift | we create loveable apps for ios, android and the web',
        description: 'Leftshift was involved with the usability, design and development of this project',
        name: 'IIFL Markets',
        tagline: 'Stock Trading on the mobile',
        para1: 'IIFL Markets allows people to trade through their phone, get in-depth analysis and expert opinions, tools for smart investors, apply for IPOs, track watchlists across NSE, BSE, MCX and NCDEX.',
        para2: 'We were involved with the usability, design, and development of the project.',
        mainurl: 'https://play.google.com/store/apps/details?id=com.indiainfoline&hl=en',
        appstoreurl: 'https://itunes.apple.com/in/app/iifl-markets/id955115541?mt=8',
        googleplayurl: 'https://play.google.com/store/apps/details?id=com.indiainfoline&hl=en',
        screenshot: 'https://leftshift.io/images/iifl/iifl-main.png',
        alttext: 'Here are screenshots of the IIFL Markets mobile applications. It helps trade on your mobile.',
        url: '/iifl-mobile-apps',
    },
    "byjus": {
        access: 'byjus',
        layout: 'project2',
        title: 'Case Study : Byjus Mobile Apps | LeftShift | we create loveable apps for ios, android and the web',
        description: 'Leftshift was involved with the usability, design and development of this project',
        name: 'Byju\'s Learning App',
        tagline: 'Fall in love with learning!',
        para1: 'This app helps you stay on top of every subject with classes from India\'s best teachers including Byju Raveendran, using state of the art technology and visualizations.',
        para2: 'We were involved with the usability, design, and development of the project.',
        mainurl: 'https://play.google.com/store/apps/details?id=com.byjus.thelearningapp&hl=en',
        appstoreurl: 'https://itunes.apple.com/in/app/byjus-the-learning-app/id1015059076?mt=8',
        googleplayurl: 'https://play.google.com/store/apps/details?id=com.byjus.thelearningapp&hl=en',
        screenshot: 'https://leftshift.io/images/byjus/byjus-main.png',
        alttext: 'Here are the screenshots of the Byjus Learning app. It helps students stay on top of subjects.',
        url: '/byjus-mobile-apps',       
    },
    "laundrie": {
        access: 'laundrie',
        layout: 'project1',
        title: 'Case Study : Laundrie Mobile Apps | LeftShift | we create loveable apps for ios, android and the web',
        description: 'Leftshift was involved with the usability, design and development of this project',
        name: 'Laundr.ie',
        tagline: 'On demand washing for Dublin',
        para1: 'Laundrie is Dublin\'s dry cleaning and washing & ironing app on demand. They pick up and delivery seven days a week at a time that works for you.',
        para2: 'We were involved with the usability, design, and development of the project.',
        mainurl: 'https://itunes.apple.com/ie/app/laundrie/id998909515?mt=8',
        appstoreurl: 'https://itunes.apple.com/ie/app/laundrie/id998909515?mt=8',
        screenshot: 'https://leftshift.io/images/laundrie/laundrie-main.png',
        alttext: 'Here are the screenshots of the Laundrie App. Its an on demand washing and ironing app for Dublin.',
        url: '/laundrie-mobile-apps',
    },
    "intown": {
        access: 'intown',
        layout: 'project2',
        title: 'Case Study : NH7 InTown Mobile Apps | LeftShift | we create loveable apps for ios, android and the web',
        description: 'Leftshift was involved with the usability, design, and development of the NH7 InTown Mobile Apps.',
        name: 'NH7 InTown',
        tagline: 'Find something to do!',
        para1: 'NH7 Intown is a comprehensive guide to dispel boredom, we help you find plays, movies, gigs, treks, workshops, food festivals and everything else in between. It makes making plans a whole lot easier.',
        para2: 'We were involved with the usability, design, and development of the project.',
        mainurl: 'https://itunes.apple.com/in/app/nh7-intown/id648303374?mt=8',
        appstoreurl: 'https://itunes.apple.com/in/app/nh7-intown/id648303374?mt=8',
        googleplayurl: 'https://play.google.com/store/apps/details?id=in.nh7.intown&hl=en',
        screenshot: 'https://leftshift.io/images/nh7/nh7intown-main.png',
        alttext: 'Here are the screenshots of the NH7 InTown application that we made with OML. It helps you find events in your city.',
        url: '/nh7-intown-mobile-apps',
    },
    "smsblocker": {
        access: 'smsblocker',
        layout: 'project1',
        title: 'Case Study : Clean Inbox Android App | LeftShift | we create loveable apps for ios, android and the web',
        description: 'Leftshift was involved with the design of the Clean Inbox Android application.',
        name: 'Clean Inbox',
        tagline: 'Blocking SMS spam on your Android',
        para1: 'The Clean Inbox is an award winning applications which helps block unwanted text messages and MMS. It has been downloaded over 2 million times on the Google Play Store and has over 32,000 5 star reviews.',
        para2: 'We were involved with the design for this project.',
        mainurl: 'https://play.google.com/store/apps/details?id=com.smsBlocker',
        appstoreurl: '',
        googleplayurl: 'https://play.google.com/store/apps/details?id=com.smsBlocker',
        screenshot: 'https://leftshift.io/images/smsblocker/smsblocker.png',
        alttext: 'Here are the screenshots for Clean Inbox. They help block SMS spam on your Android',
        url: '/smsblocker-mobile-apps',
    },
    "stepjockey": {
        access: 'stepjockey',
        layout: 'project2',
        title: 'Case Study : StepJockey Android App | LeftShift | we create loveable apps for ios, android and the web',
        description: 'Leftshift was involved with the development of the StepJockey Android application.',
        name: 'StepJockey',
        tagline: 'Labelling the world for calorie burn',
        para1: 'The StepJockey calorie tracker app is a great way to kick start physical activity and seamlessly build exercise into your daily life by taking the stairs wherever possible. The initiative is evidence-based and backed by the UK Department of Health. It uses NFC and QR codes to track the number of stairs you have been using.',
        para2: 'We were involved with the android development for this project.',
        mainurl: 'https://play.google.com/store/apps/details?id=com.stepjockey',
        appstoreurl: '',
        googleplayurl: 'https://play.google.com/store/apps/details?id=com.stepjockey',
        screenshot: 'https://leftshift.io/images/StepJockey/stepjockey.png',
        alttext: 'Here are the screenshots for StepJockey. They help count the number of calories you burn in everyday activities',
        url: '/stepjockey-mobile-apps',
    },
    "app9slides": {
        access: 'app9slides',
        layout: 'project1',
        title: 'Case Study : 9Slides iPad Apps | LeftShift | we create loveable apps for ios, android and the web',
        description: 'Leftshift was involved with the development of the 9Slides iPad application.',
        name: '9Slides',
        tagline: 'Add video to your slides',
        para1: '9Slides was among the Top Tech solutions for 2012 by Technology & Education Magazine. This app lets you import your PowerPoint and PDF presentations from SlideShare, Google-Drive, Dropbox or BOX, and let\'s you record your video which eventually gets delivered along with your presentation.',
        para2: 'We were involved with the development of the iPad project.',
        accolades: '9Slides was among the Top Tech solutions for 2012 by Technology & Education Magazine.',
        mainurl: 'https://itunes.apple.com/us/app/9slides/id586153182?mt=8',
        appstoreurl: 'https://itunes.apple.com/us/app/9slides/id586153182?mt=8',
        googleplayurl: '',
        screenshot: 'https://leftshift.io/images/9Slides/9slies.png',
        alttext: 'Here is a screenshot for 9Slides. This app helps you add videos to your presentations',
        url: '/9slides-ipad-app',
    },
    "automatic": {
        access: 'automatic',
        layout: 'project2',
        title: 'Case Study : Automatic iPhone App | LeftShift | we create loveable apps for ios, android and the web',
        description: 'Leftshift worked in tandem with Automatic\'s legendary development team to help build the Automatic application.',
        name: 'Automatic',
        tagline: 'Automatic is your Smart Driving Assistant.',
        para1: 'It wirelessly connects your car and your iPhone using Bluetooth® Low Energy, and helps you drive smarter, get feedback on your driving, know and clear the engine light, tracks trips and helps you get emergency assitance in a serious crash.',
        para2: 'We worked in tandem with Automatic\'s legendary development team to help build the app.',
        mainurl: 'https://itunes.apple.com/us/app/automatic/id596594365?mt=8',
        appstoreurl: 'https://itunes.apple.com/us/app/automatic/id596594365?mt=8',
        googleplayurl: '',
        screenshot: 'https://leftshift.io/images/automatic/automatic.png',
        alttext: 'Here are the screenshots for the Automtica app. Automatic is a smart driving assistant and has been featured on the home page of Apple',
        url: '/automatic-iphone-app',
    },
    "everest": {
        access: 'everest',
        layout: 'project1',
        title: 'Case Study : Everest Android App | LeftShift | we create loveable apps for ios, android and the web',
        description: 'Leftshift was responsible for the ideation, conceptualization, design and development of the Everest application',
        name: 'Everest App',
        tagline: 'Basecamp for Droids',
        para1: 'Everest is the first Android application to support Basecamp. It suports offline data, messages, comments, files, events and todos.',
        para2: 'This is our own product. We took care of everything from design to development.',
        mainurl: 'https://play.google.com/store/apps/details?id=com.vxtindia.android.everest.activities&hl=en',
        appstoreurl: '',
        googleplayurl: 'https://play.google.com/store/apps/details?id=com.vxtindia.android.everest.activities&hl=en',
        screenshot: 'https://leftshift.io/images/everest/everest.png',
        alttext: 'Here are the screenshots for the everest app. This was the first Android app for the new Basecamp and launched weeks after the API was released.',
        url: '/everest-basecamp-android-app',
    },
    "livephish": {
        access: 'livephish',
        layout: 'project2',
        title: 'Case Study : LivePhish iPhone App | LeftShift | we create loveable apps for ios, android and the web',
        description: 'Leftshift was involved with the usability, design, and development of Live Phish iPhone application.',
        name: 'Live Phish',
        tagline: 'Official Phish App. Voted Billboard\'s Best Music Touring App.',
        para1: 'The Live Phish app lets you browse the entire Live Phish catalog, including every concert Phish has played since 2002 plus over 50 full concerts spanning Phish\'s 25+ year career.',
        para2: 'We were involved with the usability, design, and development of the project.',
        accolades: 'Voted Billboard\'s Best Music Touring App.',
        mainurl: 'https://itunes.apple.com/us/app/live-phish/id374048661?mt=8',
        appstoreurl: 'https://itunes.apple.com/us/app/live-phish/id374048661?mt=8',
        googleplayurl: '',
        screenshot: 'https://leftshift.io/images/livephish/livephish.png',
        alttext: 'Here are the screenshots of the Live Phish app. This app reached the #1 position in Paid Music apps in the US AppStore.',
        url: '/live-phish-iphone-app',
    },
    "livemetallica": {
        access: 'livemetallica',
        layout: 'project1',
        title: 'Case Study : LiveMetallica iPhone Apps | LeftShift | we create loveable apps for ios, android and the web',
        description: 'Leftshift was involved with the usability, design, and development of the Live Metallica iPhone application.',
        name: 'Live Metallica',
        tagline: 'Official app from Metallica.',
        para1: 'Given that we were always big metallica fans, we just couldn\'t miss the chance to do their official app. You can find the latest Metallica shows throughout the World Magnetic Tour as professionally mixed audio recordings done by the band\'s own engineer on this app. Usually, new content is available hours after the show\'s last song. Almost every live note Metallica has played since 2004 is available here.',
        para2: 'We were involved with the usability, design, and development of the project.',
        mainurl: 'https://itunes.apple.com/in/app/live-metallica/id327248664?mt=8',
        appstoreurl: 'https://itunes.apple.com/in/app/live-metallica/id327248664?mt=8',
        googleplayurl: '',
        screenshot: 'https://leftshift.io/images/livemetallica/livemetallica.png',
        alttext: 'Here are the screenshots for the Live Metallica app. This is the official metallica application and got rave reviews on the AppStore.',
        url: '/live-metallica-official-iphone-app',
    }
};

exports.get = function() {
	return projects;
};